version: '3.1'

volumes:
  postgres-data: {}

services:
  articles-db:
    container_name: articles-db
    restart: always
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: articles_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - articles-network
networks:
  articles-network:
    driver: bridge
