version: "3.1"

services:
  articles-flyway:
    container_name: articles-flyway
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://articles-db:5432/articles_db?user=postgres&password=postgres -locations='filesystem:/opt/scripts' -outOfOrder=true migrate
    volumes:
      - ./scripts:/opt/scripts
    networks:
      - articles-network
networks:
  articles-network:
    driver: bridge
