version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: likebutton
    ports:
      - 27017:27017
networks:
  articles-network:
    driver: bridge
