version: '3.1'

volumes:
  postgres-data: {}

services:
  mongo:
    image: mongo:4.2-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=likebutton
    ports:
    - 27017:27017
    networks:
      - articles-network
  articles-db:
    container_name: articles-db
    restart: always
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: articles_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    depends_on:
     - 'articles_rabbitmq'
    networks:
      - articles-network
  articles-flyway:
    container_name: articles-flyway
    restart: on-failure
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://articles-db:5432/articles_db?user=postgres&password=postgres -locations='filesystem:/opt/scripts' -outOfOrder=true migrate
    volumes:
      - ./scripts:/opt/scripts
    depends_on:
      - 'articles-db'
    networks:
      - articles-network
  articles_rabbitmq:
    container_name: articles-rabbitmq
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=likebutton
      - RABBITMQ_DEFAULT_PASS=likebutton
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - articles-network
networks:
  articles-network:
    driver: bridge
