version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: likebutton
      MONGO_INITDB_ROOT_PASSWORD: likebutton

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: likebutton
      ME_CONFIG_MONGODB_ADMINPASSWORD: likebutton
    depends_on:
      - 'mongo'
networks:
  articles-network:
    driver: bridge
